const headerRoutes = [
  { name: 'Home', path: '/' },
  { name: 'Welcome to Barangay Web-based Information Management System', path: '/e-services/announcements'},
  { name: 'Registered Accounts', path: '/e-services/registered-accounts'},
  { name: 'Accounts Requests', path: '/e-services/accounts-requests'},
  { name: 'Residents Data', path: '/e-services/residents-data'},
  { name: 'My Profile', path: '/e-services/profile'},
  { name: 'Edit Password', path: '/e-services/edit-password'},
  { name: 'E-Services', path: '/e-services/services'},
  { name: 'My Requests', path: '/e-services/my-requests'},
  { name: 'Content Management', path: '/e-services/content-management'},
  { name: 'Barangay Clearance', path: '/e-services/barangay-clearance'},
  { name: 'Business Permit', path: '/e-services/business-permit'},
  { name: 'Certificate of Indigency', path: '/e-services/certificate-of-indigency'},
  { name: 'Certificate of Residency', path: '/e-services/certificate-of-residency'},
  { name: 'Blotter', path: '/e-services/blotter'},
  { name: 'Barangay Residents', path: '/e-services/barangay-residents'},
  { name: 'Head of the Family', path: '/e-services/head-family'},
  { name: 'Registered Voters', path: '/e-services/registered-voters'},
  { name: 'Male Residents', path: '/e-services/male-residents'},
  { name: 'Female Residents', path: '/e-services/female-residents'},
  { name: 'Mid Class Residents', path: '/e-services/midclass-residents'},
  { name: 'Low Class Residents', path: '/e-services/lowclass-residents'},
  { name: 'Create Banners', path: '/e-services/create-hero-banners'},
  { name: 'Create Projects', path: '/e-services/create-projects'},
  { name: 'Create News', path: '/e-services/create-news'},
  { name: 'Create Punong Barangay', path: '/e-services/create-punong-barangay'},
  { name: 'Create Barangay Officials', path: '/e-services/create-barangay-officials'},
  { name: 'Create Announcements', path: '/e-services/create-announcements'},
  { name: 'My Barangay Clearance', path: '/e-services/my-barangay-clearance'},
  { name: 'My Business Permit', path: '/e-services/my-business-permit'},
  { name: 'My Certificate Of Indigency', path: '/e-services/my-certificate-of-indigency'},
  { name: 'My Blotter', path: '/e-services/my-blotter'},
  { name: 'Contact Information', path: '/e-services/receive-contacts'},
  

];

export default headerRoutes